# A development image with extras for development.
# Don't use in production.
FROM python:3.12

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

SHELL ["/bin/bash", "-c"]

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements.txt requirements-test.txt requirements-dev.txt /app/

RUN <<EOF
  set -exo pipefail
  apt-get update
  apt-get -y upgrade
  apt-get install -y --no-install-recommends libmagic1 gettext graphviz graphviz-dev chromium
  pip install --upgrade pip
  pip install -r requirements-dev.txt
EOF

# Copy project
COPY ./app /app/

# Run the application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
