# A development image with extras for development.
# Don't use in production.
FROM python:3.12

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
COPY requirements-dev.txt /app/

RUN apt-get update && apt-get -y upgrade
RUN apt-get install --no-install-recommends -y graphviz graphviz-dev

# Install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements-dev.txt

# Copy project
COPY ./app /app/

# Run the application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
