version: '3'

services:
  sadilar-terminology-db-prod:
    image: postgres:12
    container_name: sadilar-terminology-db-prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .:/app
    ports:
      - "5432:5432"
  sadilar-terminology-web-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sadilar-terminology-web-prod
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - sadilar-terminology-db-prod
    environment:
      DJANGO_DB_HOST: ${DJANGO_DB_HOST}
      DJANGO_DB_PORT: ${DJANGO_DB_PORT}
      DJANGO_DB_NAME: ${DJANGO_DB_NAME}
      DJANGO_DB_USER: ${DJANGO_DB_USER}
      DJANGO_DB_PASSWORD: ${DJANGO_DB_PASSWORD}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
  sadilar-terminology-nginx-prod:
    build: ./nginx
    volumes:
      - ./app/static_files:/static
    ports:
      - "80:80"
    depends_on:
      - sadilar-terminology-web-prod

volumes:
  static:
