# Generated by Django 5.0.2 on 2024-04-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='languages',
            field=models.ManyToManyField(blank=True, to='general.language'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subject',
            field=models.ManyToManyField(blank=True, to='general.subject'),
        ),
    ]
