# Generated by Django 5.0.2 on 2024-07-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_historicalcustomuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
