# https://docs.docker.com/build/ci/github-actions/push-multi-registries/
name: docker_push_deploy_test

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  deploy_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to SADiLaR Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.sadilar.org
          username: ${{ vars.SADILAR_DOCKER_REPOSITORY_USER }}
          password: ${{ secrets.SADILAR_DOCKER_REPOSITORY_SECRET }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            docker.sadilar.org/term_platform:latest
      - name: Use webhook action to start deployment     
        uses: joelwmale/webhook-action@2.3.2
        with:
          url: https://api.bitbucket.org/2.0/repositories/team_sadilar/ansible/pipelines/
          headers: '{"Authorization": "Bearer ${{ secrets.BITBUCKET_PIPELINE_SECRET }}"}'
          body: '{"target": {"ref_type": "branch", "type": "pipeline_ref_target", "ref_name": "master", "selector": {"type": "custom", "pattern": "deploy_term_platform_test" }   }}'
