# https://docs.docker.com/build/ci/github-actions/push-multi-registries/
name: docker_push_prod

on:
  push:
    tags:
      - v**

jobs:
  docker_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to SADiLaR Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.sadilar.org
          username: ${{ vars.SADILAR_DOCKER_REPOSITORY_USER }}
          password: ${{ secrets.SADILAR_DOCKER_REPOSITORY_SECRET }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            docker.sadilar.org/term_platform:prod
