name: Testing Django
on: [ pull_request, push ] # activates the workflow when there is a push or pull request in the repo
jobs:
  test_project:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: Run linting tools
        run: |
          cd app/
          ruff format .
      - name: Create logging folder
        run: |
          sudo  mkdir -p /logging
          sudo chown runner:runner /logging
      - name: Run Tests
        run: |
          cp .env.testing app/.env
          cd app/
          mkdir -p static_files
          python manage.py test
      - name: Manager Check
        run: |
          cd app/
          python manage.py check
