# Generated by Django 5.0.2 on 2024-04-19 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_documentfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentfile',
            old_name='Institution',
            new_name='institution',
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='document_type',
            field=models.CharField(choices=[('Glossary', 'Glossary'), ('Policy', 'Policy')], max_length=200),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='license',
            field=models.CharField(choices=[('(c)', 'All rights reserved'), ('CC0', 'No rights reserved'), ('CC BY', 'Creative Commons Attribution'), ('CC BY-SA', 'Creative Commons Attribution-ShareAlike'), ('CC BY-NC', 'Creative Commons Attribution-NonCommercial'), ('CC BY-NC-SA', 'Creative Commons Attribution-NonCommercial-ShareAlike')], default='(c)', help_text='\n            <a\n              href="https://creativecommons.org/share-your-work/cclicenses/"\n              rel="noreferrer"\n              target="_blank"\n            >\n                    More information about Creative Commons licenses.\n            </a>\'\n    ', max_length=200),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='PDF files up to 10MB are allowed.', upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='language',
            name='iso_code',
            field=models.CharField(help_text='The 2 or 3 letter code from ISO 639.', max_length=50, unique=True, verbose_name='ISO code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
