# Generated by Django 5.0.2 on 2024-05-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_institution_logo_alter_project_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='document_data',
            field=models.TextField(blank=True),
        ),
    ]
