# Generated by Django 5.0.2 on 2024-07-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '00010_documentfile_search_vector_trigger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentfile',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='historicaldocumentfile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Document', 'verbose_name_plural': 'historical Documents'},
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='document_type',
            field=models.CharField(choices=[('Glossary', 'Glossary'), ('Policy', 'Policy')], max_length=200, verbose_name='document category'),
        ),
        migrations.AlterField(
            model_name='historicaldocumentfile',
            name='document_type',
            field=models.CharField(choices=[('Glossary', 'Glossary'), ('Policy', 'Policy')], max_length=200, verbose_name='document category'),
        ),
    ]
