# Generated by Django 5.0.8 on 2024-11-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_rename_documentfile_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('can_edit_fulltext', 'Can edit document fulltext (used for search)')], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
    ]
