# Generated by Django 5.0.8 on 2025-01-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_alter_document_document_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Glossary', 'Glossary'), ('Policy', 'Policy'), ('Term list', 'Term list')], max_length=200, verbose_name='document category'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='document_type',
            field=models.CharField(choices=[('Glossary', 'Glossary'), ('Policy', 'Policy'), ('Term list', 'Term list')], max_length=200, verbose_name='document category'),
        ),
    ]
