# Generated by Django 5.2.4 on 2025-08-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_alter_document_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='standardised',
            field=models.BooleanField(default=False, verbose_name='authenticated and standardised'),
        ),
        migrations.AddField(
            model_name='document',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='standardised',
            field=models.BooleanField(default=False, verbose_name='authenticated and standardised'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
    ]
