# Generated by Django 5.2.13 on 2026-04-28 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0017_document_standardised_document_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='PDF and XLSX files up to 10MB are allowed.', upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'xlsx'])], verbose_name='uploaded file'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='uploaded_file',
            field=models.TextField(blank=True, help_text='PDF and XLSX files up to 10MB are allowed.', max_length=100, validators=[django.core.validators.FileExtensionValidator(['pdf', 'xlsx'])], verbose_name='uploaded file'),
        ),
    ]
